language: ruby

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - echo $PATH
  - cp test/ffprobe /home/travis/bin

script: rake

sudo: false

addons:
  apt:
    packages:
    - ffmpeg

addons:
  code_climate:
    repo_token: e319ec7d18fb8e1f05b460c3ef8fac58af3844d7bfa3d44de6b82eb874bb3e31

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-head
